services:
  - type: web
    name: bank-truth-calculator
    runtime: docker
    repo: https://github.com/davesuy/bank-truth-calculator
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Bank Truth Calculator
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:2azluL8LXJhWal35l/a74fyIvdHsMsXBwRMnjLIEzqw=
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://bank-truth-calculator-1.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file


